apiVersion: v1
kind: Service
metadata:
  name: tool-backend-svc
  namespace: devmeet
spec:
  selector:
    app: tool-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
