global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: main-backend
    metrics_path: /api/metrics
    static_configs:
      - targets: ["localhost:8080"]

  - job_name: tool-backend
    metrics_path: /tool/metrics
    static_configs:
      - targets: ["localhost:8000"]