apiVersion: v1
kind: ConfigMap
metadata:
  name: main-backend-config
  namespace: devmeet
data:
  # 기본 설정
  NODE_HOST: "0.0.0.0"
  NODE_ENV: "production"
  NODE_BACKEND_SERVER: "https://www.devmeet.p-e.kr"
  NODE_FRONTEND_SERVER: "https://www.devmeet.p-e.kr"

  # cors 정책
  NODE_ALLOWED_ORIGIN: "https://www.devmeet.p-e.kr"
  NODE_ALLOWED_METHODS: "GET,POST,PUT,DELETE,PATCH"
  NODE_ALLOWED_HEADERS: "Content-Type, Accept, Authorization"
  NODE_ALLOWED_CREDENTIALS: "true"
  NODE_ALLOWED_EXPOSE_HEADERS: "x-access-token"

  # DB
  NODE_APP_DATABASE_HOST: "172.16.5.7"

  # Kafka
  NODE_APP_KAFKA_BROKERS: "172.16.5.9:9092"

  # S3
  NODE_APP_AWS_BUCKET_NAME: "owl-cloud-deploy-disk"
  NODE_APP_AWS_REGION_NAME: "ap-northeast-2"