services:
  mysql:
    image: mysql:8.0
    container_name: local_mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d # mysql에 설정을 위한 폴더
    restart: unless-stopped

  redis:
    image: redis:7.0-alpine
    container_name: local_redis
    ports:
      - "6381:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - ./redis/data:/data
      - ./redis/reds.conf:/usr/local/etc/redis/redis.conf:ro # redis에 설정 파일이 들어갈 예정i
    restart: unless-stopped
