# 세팅을 위한 docker compose 
services:
  main-backend-app-1:
    container_name: main-backend-app-1
    build: 
      context: ./rep/main_backend
      dockerfile: Dockerfile
    env_file:
      - ./.env.backend
    networks:
      - clobby-network
  
  main-backend-app-2:
    container_name: main-backend-app-2
    build: 
      context: ./rep/main_backend
      dockerfile: Dockerfile
    env_file:
      - ./.env.backend
    networks:
      - clobby-network

  main-backend-app-3:
    container_name: main-backend-app-3
    build: 
      context: ./rep/main_backend
      dockerfile: Dockerfile
    env_file:
      - ./.env.backend
    networks:
      - clobby-network

  main-backend-nginx:
    container_name: main-backend-nginx
    image: nginx:latest
    volumes:
      - ./nginx.backend.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - main-backend-app-1
      - main-backend-app-2
      - main-backend-app-3
    networks:
      - clobby-network
    restart: unless-stopped

  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - clobby-network

  frontend-nginx:
    container_name: frontend-nginx
    image: nginx:latest
    volumes:
      - ./nginx.frontend.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
    networks:
      - clobby-network
    restart: unless-stopped

  gateway:
    image: nginx:latest
    container_name: gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.gateway.conf:/etc/nginx/conf.d/default.conf:ro 
      - ./etc/certbot/www:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - main-backend-nginx
      - frontend-nginx
    networks:
      - clobby-network

networks:
  clobby-network:
    driver: bridge